# Generated by Django 5.1.6 on 2025-04-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="old_cart",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
